# Generated by Django 5.2.8 on 2025-11-18 19:22

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_model', models.CharField(blank=True, default=None, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 3 character')], verbose_name='Product Brand')),
                ('name', models.CharField(default=None, max_length=1500, validators=[django.core.validators.MinLengthValidator(2, 'the field must contain at least 2 character')], verbose_name='Product Name')),
                ('description', models.TextField(blank=True, default=None, max_length=1500, null=True, validators=[django.core.validators.MinLengthValidator(10, 'the field must contain at least 10 characters')])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Product Price')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Dicount')),
                ('slug', models.SlugField(blank=True, max_length=1500, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('favourites', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='members.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, validators=[django.core.validators.MinLengthValidator(3, 'the field must contain at least 20 character')], verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Laptops',
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('screen_size', models.CharField(blank=True, max_length=50)),
                ('battery_capacity', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Phones',
            },
            bases=('store.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('last_restocked', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Vary Good'), (5, '5 - Excellent')], null=True)),
                ('body', models.TextField(max_length=300)),
                ('slug', models.SlugField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'user')},
            },
        ),
    ]
