# Generated by Django 5.2.8 on 2025-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_description_category_parent"),
    ]
