# Generated by Django 5.2.8 on 2025-11-25 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(related_name='user_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
