# Generated by Django 5.2.8 on 2025-11-25 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visitors',
            field=models.ManyToManyField(related_name='visited_merchants', to=settings.AUTH_USER_MODEL),
        ),
    ]
