# Generated by Django 5.2.8 on 2025-11-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='visitors',
        ),
    ]
