# Generated by Django 5.2.8 on 2025-11-26 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_visitors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visitors',
            field=models.ManyToManyField(related_name='product_visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
