# Generated by Django 5.2.8 on 2025-11-26 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_visitors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='site_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_visitor_count', models.IntegerField(default=0)),
                ('auth_visitors', models.ManyToManyField(blank=True, related_name='site_visists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
