# Generated by Django 5.2.8 on 2025-11-26 19:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_site_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='site_state',
            new_name='SiteStats',
        ),
    ]
