# Generated by Django 5.2.8 on 2025-11-28 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_site_state_sitestats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='user_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='product_visitors', to=settings.AUTH_USER_MODEL),
        ),
    ]
