# Generated by Django 5.2.8 on 2025-12-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('clothing_type', models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Jeans', 'Jeans'), ('Dress', 'Dress'), ('Jacket', 'Jacket'), ('Sweater', 'Sweater')], max_length=50)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=20)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(help_text='e.g., Cotton, Polyester', max_length=100)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter'), ('All Season', 'All Season')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Clothing',
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('headphone_type', models.CharField(choices=[('Over-Ear', 'Over-Ear'), ('On-Ear', 'On-Ear'), ('In-Ear', 'In-Ear'), ('Earbuds', 'Earbuds')], max_length=50)),
                ('connection_type', models.CharField(choices=[('Wireless', 'Wireless'), ('Wired', 'Wired')], max_length=20)),
                ('noise_cancellation', models.BooleanField(default=False)),
                ('battery_life', models.IntegerField(blank=True, help_text='In hours', null=True)),
                ('driver_size', models.IntegerField(blank=True, help_text='In mm', null=True)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Headphones',
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('shoe_type', models.CharField(choices=[('Sneakers', 'Sneakers'), ('Boots', 'Boots'), ('Sandals', 'Sandals'), ('Formal', 'Formal'), ('Sports', 'Sports')], max_length=50)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=20)),
                ('size', models.IntegerField(help_text='US size')),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(help_text='e.g., Leather, Canvas', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Shoes',
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='SportEquipment',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('sport_type', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Gym', 'Gym'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming')], max_length=50)),
                ('equipment_type', models.CharField(help_text='e.g., Ball, Racket, Dumbbell', max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.FloatField(blank=True, help_text='In kg', null=True)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Sport Equipment',
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('screen_size', models.FloatField(help_text='In inches')),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField(help_text='In GB')),
                ('storage', models.IntegerField(help_text='In GB')),
                ('battery_capacity', models.IntegerField(help_text='In mAh')),
                ('camera', models.CharField(max_length=50)),
                ('operating_system', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Windows', 'Windows')], max_length=50)),
                ('has_sim_card', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tablets',
            },
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('watch_type', models.CharField(choices=[('Analog', 'Analog'), ('Digital', 'Digital'), ('Smart Watch', 'Smart Watch')], max_length=50)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], max_length=20)),
                ('strap_material', models.CharField(choices=[('Leather', 'Leather'), ('Metal', 'Metal'), ('Rubber', 'Rubber'), ('Fabric', 'Fabric')], max_length=50)),
                ('water_resistant', models.BooleanField(default=False)),
                ('display_type', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_type', models.CharField(choices=[('Quartz', 'Quartz'), ('Automatic', 'Automatic'), ('Rechargeable', 'Rechargeable')], max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Watches',
            },
            bases=('store.product',),
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='storage',
        ),
        migrations.AddField(
            model_name='laptop',
            name='battery_life',
            field=models.IntegerField(default=1, help_text='In hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='graphics_card',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(choices=[('Windows 11', 'Windows 11'), ('Windows 10', 'Windows 10'), ('macOS', 'macOS'), ('Linux', 'Linux')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='processor_generation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='screen_size',
            field=models.FloatField(default=1, help_text='In inches'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage_capacity',
            field=models.IntegerField(default=1, help_text='In GB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('Hybrid', 'Hybrid')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='weight',
            field=models.FloatField(default=1, help_text='In kg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='front_camera',
            field=models.CharField(default=1, help_text='e.g., 12MP', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='network',
            field=models.CharField(choices=[('4G', '4G'), ('5G', '5G')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='operating_system',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='processor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(default=1, help_text='In GB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='rear_camera',
            field=models.CharField(default=1, help_text='e.g., 48MP + 12MP', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='screen_type',
            field=models.CharField(choices=[('AMOLED', 'AMOLED'), ('LCD', 'LCD'), ('OLED', 'OLED'), ('IPS', 'IPS')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='storage',
            field=models.IntegerField(default=1, help_text='In GB'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(help_text='e.g., Intel Core i7', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(help_text='In GB'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery_capacity',
            field=models.IntegerField(help_text='In mAh'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_size',
            field=models.FloatField(help_text='In inches'),
        ),
    ]
