# Generated by Django 5.2.8 on 2025-12-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
