# Generated by Django 5.2.8 on 2025-12-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
