# Generated by Django 5.2.8 on 2025-12-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_views_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Yes/No'), ('choice', 'Dropdown')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='headphone',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='product_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='sportequipment',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='model_name',
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Clothing',
        ),
        migrations.DeleteModel(
            name='Headphone',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.DeleteModel(
            name='SportEquipment',
        ),
        migrations.DeleteModel(
            name='Tablet',
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
