# Generated by Django 5.2.8 on 2025-12-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_categoryattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='store.product'),
        ),
    ]
