# Generated by Django 5.2.8 on 2025-11-18 19:22

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('summary_shipping_address', models.TextField(default=None, max_length=15000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_shipped', models.DateTimeField(blank=True, null=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='payment.order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shipping_full_name', models.CharField(max_length=255)),
                ('shipping_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('shipping_address1', models.CharField(max_length=400, verbose_name='Address')),
                ('shipping_address2', models.CharField(max_length=400, verbose_name='Address')),
                ('building_name', models.CharField(max_length=400, null=True, verbose_name='Building Name')),
                ('shipping_phone', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(11, 'The Field Must be contain 11 Numbers')])),
                ('shipping_city', models.CharField(blank=True, max_length=255)),
                ('shipping_state', models.CharField(blank=True, max_length=255)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=255)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='payment.shippingaddress'),
        ),
    ]
