# Generated by Django 5.2.8 on 2025-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered',
            new_name='confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
