# Generated by Django 5.2.8 on 2025-12-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_delivered_order_confirmed_order_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
    ]
