# Generated by Django 5.2.8 on 2025-12-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_order_confirmed_remove_order_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('shipped', 'Shipped')], default='pending', max_length=20),
        ),
    ]
