# Generated by Django 5.2.8 on 2025-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('marchent', 'Marchent'), ('customer', 'Customer')], default='customer', max_length=255),
        ),
    ]
