# Generated by Django 5.2.8 on 2025-11-25 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='visitors',
            field=models.ManyToManyField(related_name='visited_merchants', to=settings.AUTH_USER_MODEL),
        ),
    ]
