# Generated by Django 5.2.8 on 2025-11-28 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_merchant_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='visited_merchants', to=settings.AUTH_USER_MODEL),
        ),
    ]
