# Generated by Django 5.2.8 on 2025-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_merchant_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('merchant', 'Merchant'), ('customer', 'Customer')], default='customer', max_length=255),
        ),
    ]
